'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'StronglyTypedResourceBuilder generó automáticamente esta clase
'a través de una herramienta como ResGen o Visual Studio.
'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
'con la opción /str o recompile su proyecto de VS.
'''<summary>
'''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Public Class Messages
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MWBot.net.Messages", GetType(Messages).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
    '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Abuse filter triggered on &apos;{0}&apos;..
    '''</summary>
    Public Shared ReadOnly Property AbuseFilter() As String
        Get
            Return ResourceManager.GetString("AbuseFilter", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a MWBot.net.
    '''</summary>
    Public Shared ReadOnly Property BotEngine() As String
        Get
            Return ResourceManager.GetString("BotEngine", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Checking user {0}.
    '''</summary>
    Public Shared ReadOnly Property CheckingUser() As String
        Get
            Return ResourceManager.GetString("CheckingUser", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Checking users..
    '''</summary>
    Public Shared ReadOnly Property CheckingUsers() As String
        Get
            Return ResourceManager.GetString("CheckingUsers", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Malformed config file..
    '''</summary>
    Public Shared ReadOnly Property ConfigError() As String
        Get
            Return ResourceManager.GetString("ConfigError", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Bot edit..
    '''</summary>
    Public Shared ReadOnly Property DefaultSumm() As String
        Get
            Return ResourceManager.GetString("DefaultSumm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Done, {0} pages returned..
    '''</summary>
    Public Shared ReadOnly Property DoneXPagesReturned() As String
        Get
            Return ResourceManager.GetString("DoneXPagesReturned", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Edit conflit on &apos;{0}&apos;..
    '''</summary>
    Public Shared ReadOnly Property EditConflict() As String
        Get
            Return ResourceManager.GetString("EditConflict", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error creating file &apos;{0}&apos;..
    '''</summary>
    Public Shared ReadOnly Property FileCreateErr() As String
        Get
            Return ResourceManager.GetString("FileCreateErr", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error saving &apos;{0}&apos;..
    '''</summary>
    Public Shared ReadOnly Property FileSaveErr() As String
        Get
            Return ResourceManager.GetString("FileSaveErr", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Getting the last revid of {0} pages..
    '''</summary>
    Public Shared ReadOnly Property GetLastrevIDs() As String
        Get
            Return ResourceManager.GetString("GetLastrevIDs", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Loading page extract of &apos;{0}&apos;..
    '''</summary>
    Public Shared ReadOnly Property GetPageExtract() As String
        Get
            Return ResourceManager.GetString("GetPageExtract", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Loading {0} pages extract..
    '''</summary>
    Public Shared ReadOnly Property GetPagesExtract() As String
        Get
            Return ResourceManager.GetString("GetPagesExtract", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a ==================== MWBot.net {0} ====================.
    '''</summary>
    Public Shared ReadOnly Property GreetingMsg() As String
        Get
            Return ResourceManager.GetString("GreetingMsg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a The url is invalid..
    '''</summary>
    Public Shared ReadOnly Property InvalidUrl() As String
        Get
            Return ResourceManager.GetString("InvalidUrl", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a The user &apos;{0}&apos; is invalid..
    '''</summary>
    Public Shared ReadOnly Property InvalidUser() As String
        Get
            Return ResourceManager.GetString("InvalidUser", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Loading config.
    '''</summary>
    Public Shared ReadOnly Property LoadingConfig() As String
        Get
            Return ResourceManager.GetString("LoadingConfig", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Loading ORES score from revid {0}..
    '''</summary>
    Public Shared ReadOnly Property LoadingOres() As String
        Get
            Return ResourceManager.GetString("LoadingOres", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Login failed.
    '''</summary>
    Public Shared ReadOnly Property LoginError() As String
        Get
            Return ResourceManager.GetString("LoginError", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Login ID: .
    '''</summary>
    Public Shared ReadOnly Property LoginID() As String
        Get
            Return ResourceManager.GetString("LoginID", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Login result: .
    '''</summary>
    Public Shared ReadOnly Property LoginResult() As String
        Get
            Return ResourceManager.GetString("LoginResult", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Max retry count reached on {0}..
    '''</summary>
    Public Shared ReadOnly Property MaxRetryCount() As String
        Get
            Return ResourceManager.GetString("MaxRetryCount", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Network error: .
    '''</summary>
    Public Shared ReadOnly Property NetworkError() As String
        Get
            Return ResourceManager.GetString("NetworkError", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Archive box page name (with namespace):.
    '''</summary>
    Public Shared ReadOnly Property NewArchiveBoxTemplate() As String
        Get
            Return ResourceManager.GetString("NewArchiveBoxTemplate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Archive page message (with namespace):.
    '''</summary>
    Public Shared ReadOnly Property NewArchiveMessageTemplate() As String
        Get
            Return ResourceManager.GetString("NewArchiveMessageTemplate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Auto archive &apos;do not archive&apos; page name (with namespace):.
    '''</summary>
    Public Shared ReadOnly Property NewAutoArchiveDoNotArchivePageName() As String
        Get
            Return ResourceManager.GetString("NewAutoArchiveDoNotArchivePageName", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Auto archive &apos;programmed archive&apos; page name (with namespace):.
    '''</summary>
    Public Shared ReadOnly Property NewAutoArchiveProgrammedArchivePageName() As String
        Get
            Return ResourceManager.GetString("NewAutoArchiveProgrammedArchivePageName", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Auto archive template page name (with namespace): .
    '''</summary>
    Public Shared ReadOnly Property NewAutoArchiveTemplatePagename() As String
        Get
            Return ResourceManager.GetString("NewAutoArchiveTemplatePagename", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Auto signature template page name (with namespace):.
    '''</summary>
    Public Shared ReadOnly Property NewAutoSignatureTemplatePageName() As String
        Get
            Return ResourceManager.GetString("NewAutoSignatureTemplatePageName", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Bot name: .
    '''</summary>
    Public Shared ReadOnly Property NewBotName() As String
        Get
            Return ResourceManager.GetString("NewBotName", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Wiki BOT password: .
    '''</summary>
    Public Shared ReadOnly Property NewBotPassword() As String
        Get
            Return ResourceManager.GetString("NewBotPassword", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error creating a new config file.
    '''</summary>
    Public Shared ReadOnly Property NewConfigFileError() As String
        Get
            Return ResourceManager.GetString("NewConfigFileError", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a There is no config file, please fill the following data or close the program and manually create a new config file..
    '''</summary>
    Public Shared ReadOnly Property NewConfigMessage() As String
        Get
            Return ResourceManager.GetString("NewConfigMessage", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Wiki user name: .
    '''</summary>
    Public Shared ReadOnly Property NewUserName() As String
        Get
            Return ResourceManager.GetString("NewUserName", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Wiki API Url: .
    '''</summary>
    Public Shared ReadOnly Property NewWikiMainApiUrl() As String
        Get
            Return ResourceManager.GetString("NewWikiMainApiUrl", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Wiki Url: .
    '''</summary>
    Public Shared ReadOnly Property NewWikiMainUrl() As String
        Get
            Return ResourceManager.GetString("NewWikiMainUrl", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a This bot cannot edit on &apos;{0}&apos;..
    '''</summary>
    Public Shared ReadOnly Property NoBots() As String
        Get
            Return ResourceManager.GetString("NoBots", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No config file.
    '''</summary>
    Public Shared ReadOnly Property NoConfigFile() As String
        Get
            Return ResourceManager.GetString("NoConfigFile", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No text with date format found.
    '''</summary>
    Public Shared ReadOnly Property NoDateMatch() As String
        Get
            Return ResourceManager.GetString("NoDateMatch", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Cannot get ORES score of revid {0}. EX: {1}.
    '''</summary>
    Public Shared ReadOnly Property OresFailed() As String
        Get
            Return ResourceManager.GetString("OresFailed", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a ORES score from revid {0}. DMG:{1} /GF:{2} .
    '''</summary>
    Public Shared ReadOnly Property OresLoaded() As String
        Get
            Return ResourceManager.GetString("OresLoaded", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Server error on ORES query score from revid {0} (invalid diff?).
    '''</summary>
    Public Shared ReadOnly Property OresQueryError() As String
        Get
            Return ResourceManager.GetString("OresQueryError", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a ORES query from revid {0} EX: {1}.
    '''</summary>
    Public Shared ReadOnly Property OresQueryEx() As String
        Get
            Return ResourceManager.GetString("OresQueryEx", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a ORES query for revid {0} done. GF: {1} DMG: {2}.
    '''</summary>
    Public Shared ReadOnly Property OresQueryResult() As String
        Get
            Return ResourceManager.GetString("OresQueryResult", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Warning: The page &apos;{0}&apos; does not exist yet!.
    '''</summary>
    Public Shared ReadOnly Property PageDoesNotExist() As String
        Get
            Return ResourceManager.GetString("PageDoesNotExist", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Page &apos;{0}&apos; loaded..
    '''</summary>
    Public Shared ReadOnly Property PageLoaded() As String
        Get
            Return ResourceManager.GetString("PageLoaded", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Notice: The page &apos;{0}&apos; does not have a thumbnail..
    '''</summary>
    Public Shared ReadOnly Property PageNoThumb() As String
        Get
            Return ResourceManager.GetString("PageNoThumb", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a POST exception on &apos;{0}&apos;. EX: {1}.
    '''</summary>
    Public Shared ReadOnly Property POSTEX() As String
        Get
            Return ResourceManager.GetString("POSTEX", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Press any key to exit.
    '''</summary>
    Public Shared ReadOnly Property PressKey() As String
        Get
            Return ResourceManager.GetString("PressKey", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Page with revid {0} loaded..
    '''</summary>
    Public Shared ReadOnly Property PRevLoaded() As String
        Get
            Return ResourceManager.GetString("PRevLoaded", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Reason: .
    '''</summary>
    Public Shared ReadOnly Property Reason() As String
        Get
            Return ResourceManager.GetString("Reason", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Removing all references to &apos;{0}&apos;..
    '''</summary>
    Public Shared ReadOnly Property RemovingRefs() As String
        Get
            Return ResourceManager.GetString("RemovingRefs", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Requesting token.
    '''</summary>
    Public Shared ReadOnly Property RequestingToken() As String
        Get
            Return ResourceManager.GetString("RequestingToken", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Error saving the config..
    '''</summary>
    Public Shared ReadOnly Property SaveConfigError() As String
        Get
            Return ResourceManager.GetString("SaveConfigError", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Signing in.
    '''</summary>
    Public Shared ReadOnly Property SigninIn() As String
        Get
            Return ResourceManager.GetString("SigninIn", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Anti spam abuse filter triggered on &apos;{0}&apos;..
    '''</summary>
    Public Shared ReadOnly Property SpamBlackList() As String
        Get
            Return ResourceManager.GetString("SpamBlackList", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Edit on &apos;{0}&apos; successful..
    '''</summary>
    Public Shared ReadOnly Property SuccessfulEdit() As String
        Get
            Return ResourceManager.GetString("SuccessfulEdit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Successful operation..
    '''</summary>
    Public Shared ReadOnly Property SuccessfulOperation() As String
        Get
            Return ResourceManager.GetString("SuccessfulOperation", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a (Bot) Replacing &apos;{0}&apos; with &apos;{1}&apos; {2}..
    '''</summary>
    Public Shared ReadOnly Property TextReplaced() As String
        Get
            Return ResourceManager.GetString("TextReplaced", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Token obtained.
    '''</summary>
    Public Shared ReadOnly Property TokenObtained() As String
        Get
            Return ResourceManager.GetString("TokenObtained", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Trying to save &apos;{0}&apos;..
    '''</summary>
    Public Shared ReadOnly Property TryingToSave() As String
        Get
            Return ResourceManager.GetString("TryingToSave", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Unexpected exception: {0}.
    '''</summary>
    Public Shared ReadOnly Property UnexpectedEX() As String
        Get
            Return ResourceManager.GetString("UnexpectedEX", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Unsuccessful operation..
    '''</summary>
    Public Shared ReadOnly Property UnsuccessfulOperation() As String
        Get
            Return ResourceManager.GetString("UnsuccessfulOperation", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a User {0} is blocked..
    '''</summary>
    Public Shared ReadOnly Property UserBlocked() As String
        Get
            Return ResourceManager.GetString("UserBlocked", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a User {0} is inactive..
    '''</summary>
    Public Shared ReadOnly Property UserInactive() As String
        Get
            Return ResourceManager.GetString("UserInactive", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a User {0} does not exist..
    '''</summary>
    Public Shared ReadOnly Property UserInexistent() As String
        Get
            Return ResourceManager.GetString("UserInexistent", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a {0} has just edited..
    '''</summary>
    Public Shared ReadOnly Property UserJustEdited() As String
        Get
            Return ResourceManager.GetString("UserJustEdited", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a User name: .
    '''</summary>
    Public Shared ReadOnly Property UserName() As String
        Get
            Return ResourceManager.GetString("UserName", resourceCulture)
        End Get
    End Property
End Class
